# Name of your application. Used to uniquely configure containers.
service: my-app

# Name of the container image.
image: my-user/myapp

# Deploy to these servers.
servers:
  # IP address of server, optionally use env variable.
  web:
    - 192.168.0.1
#   - <%= ENV['KAMAL_DEPLOY_IP'] %>


# Enable SSL auto certification via Let's Encrypt (and allow for multiple apps on one server).
# If using something like Cloudflare, it is recommended to set encryption mode
# in Cloudflare's SSL/TLS setting to "Full" to enable end-to-end encryption.
proxy:
  ssl: true
  host: my-app.example.com
  # kamal-proxy connects to your container over port 80, use `app_port` to specify a different port.
  app_port: 8080

  healthcheck:
    interval: 3
    path: /metadata
    timeout: 3

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

volumes:
  - "/opt/docker/MyApp/App_Data:/app/App_Data"

#accessories:
#  litestream:
#    roles: ["web"]
#    image: litestream/litestream
#    files: ["config/litestream.yml:/etc/litestream.yml"]
#    volumes: ["/opt/docker/MyApp/App_Data:/data"]
#    cmd: replicate
#    env:
#      secret:
#        - ACCESS_KEY_ID
#        - SECRET_ACCESS_KEY
